### Create a new user

POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email":"test@test.com",
  "password":"password"
}

### Find a particular user with a given ID

GET http://localhost:3000/auth/1

### Find all users with a given email

GET http://localhost:3000/auth/?email=hullo@world.com

### Delete a user with a given ID

DELETE http://localhost:3000/auth/1

### Update a user with a given ID

PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "email":"hello@world.com"
}

### Log in with an email and password

POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email":"test@pepe.com",
  "password":"password"
}

### Get the current signed in user

GET http://localhost:3000/auth/whoami

### Sign out

POST http://localhost:3000/auth/signout
content-type: application/json